@extends('layouts.app')
@section('content')
<style>
      body {
      background-color: #f8f9fa;
    }
    .card {
      margin-bottom: 1.5rem;
      margin-top: 1.5rem;
      transition: all .5s ease;
    }
    .card:hover{
      transform: translateY(-5px);
    }
    .card .body1{
      background: white;
      box-shadow: 0 15px 30px rgba(0, 0, 0, 0.25);
      border-radius: 8px;
      margin-bottom: 10px;
    }
    .map-placeholder {
      background-color: #e9ecef;
      height: 300px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: #6c757d;
      font-size: 1.25rem;
      border-radius: 0.375rem;
    }
    .table-responsive {
      max-height: 300px;
      overflow-y: auto;
    }
    .container-fluid {
           transition: transform 0.3s ease, box-shadow 0.3s ease;
    }
            @keyframes slideUp {
  from {
    transform: translateY(100px);
    opacity: 0;
  }
  to {
    transform: translateY(0);   
    opacity: 1;
  }
}
.slide-up {
  animation: slideUp 0.6s ease-out;
}


  </style>

  <div class="container-fluid slide-up mt-4">
    <h2 class="mb-4">Dashboard</h2>

    <!-- Stats Cards -->
    <div class="row g-4">
        <div class="col-md-3">
            <div class="card shadow-lg border-0 rounded-3">
                <div class="card-body">
                    <h6 class="text-muted">Total Vehicles</h6>
                    <h3 class="fw-bold">120</h3>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card shadow-lg border-0 rounded-3">
                <div class="card-body">
                    <h6 class="text-muted">Active Dispatches</h6>
                    <h3 class="fw-bold">45</h3>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card shadow-lg border-0 rounded-3">
                <div class="card-body">
                    <h6 class="text-muted">Pending Maintenance</h6>
                    <h3 class="fw-bold">12</h3>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card shadow-lg border-0 rounded-3">
                <div class="card-body">
                    <h6 class="text-muted">Reports</h6>
                    <h3 class="fw-bold">30</h3>
                </div>
            </div>
        </div>
    </div>

    <!-- Recent Activity + Chart -->
    <div class="row mt-4">
        <div class="col-lg-8">
            <div class="card shadow-sm border-0 rounded-3 mb-4">
                <div class="card-header bg-white border-0">
                    <h6 class="mb-0">Recent Activities</h6>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Vehicle <strong>ABC-123</strong> dispatched at 10:00 AM</li>
                        <li class="list-group-item">Maintenance scheduled for <strong>XYZ-456</strong></li>
                        <li class="list-group-item">New report generated by <strong>Admin</strong></li>
                        <li class="list-group-item">Vehicle <strong>JKL-789</strong> returned to depot</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card shadow-sm border-0 rounded-3">
                <div class="card-header bg-white border-0">
                    <h6 class="mb-0">Monthly Summary</h6>
                </div>
                <div class="card-body">
                    <!-- Placeholder Chart -->
                    <div class="text-center text-muted p-5 border rounded-3">
                        <span>Chart Placeholder</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

  <!-- Bootstrap JS Bundle (includes Popper) -->

  <!-- Chart.js for Fuel Consumption Chart -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
    const ctx = document.getElementById('fuelChart').getContext('2d');
    const fuelChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: ['6 days ago', '5 days ago', '4 days ago', '3 days ago', '2 days ago', 'Yesterday', 'Today'],
        datasets: [{
          label: 'Fuel (Liters)',
          data: [120, 115, 130, 125, 110, 105, 100],
          fill: true,
          backgroundColor: 'rgba(13, 110, 253, 0.2)',
          borderColor: 'rgba(13, 110, 253, 1)',
          tension: 0.3,
          pointRadius: 4,
          pointHoverRadius: 6,
        }]
      },
      options: {
        responsive: true,
        scales: {
          y: {
            beginAtZero: true,
            title: {
              display: true,
              text: 'Liters'
            }
          },
          x: {
            title: {
              display: true,
              text: 'Day'
            }
          }
        },
        plugins: {
          legend: {
            display: true,
            position: 'top',
          }
        }
      }
    });
  </script>

  

@endsection('content')
